---
name: deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2.10.1
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
